"""add track language_raw column

Revision ID: 2cecca291ed0
Revises: d0f4d45356ad
Create Date: 2026-07-13 03:13:18.847592

Backfills language_raw from the existing language column for pre-existing
rows. This is a best-available approximation, not a perfect reconstruction:
before this change, ffprobe-sourced tracks stored language completely
unnormalized (so today's language value IS effectively raw for those), while
sidecar-sourced tracks (.en.srt etc.) already had their true original token
discarded during the old normalization step. language itself is only
genuinely renormalized (and language_raw genuinely raw going forward) for a
given file the next time it's re-probed via a rescan -- this migration does
not attempt to renormalize existing data.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2cecca291ed0'
down_revision: str | Sequence[str] | None = 'd0f4d45356ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('language_raw', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE tracks SET language_raw = language WHERE language IS NOT NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'language_raw')
    # ### end Alembic commands ###
