"""add provider metadata columns to media_items

Revision ID: 3c2759616df0
Revises: 2cecca291ed0
Create Date: 2026-07-13 19:11:51.838688

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c2759616df0'
down_revision: str | Sequence[str] | None = '2cecca291ed0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('anilist_id', sa.Integer(), nullable=True))
    op.add_column('media_items', sa.Column('provider_source', sa.String(length=16), nullable=True))
    op.add_column('media_items', sa.Column('provider_is_anime', sa.Boolean(), nullable=True))
    op.add_column('media_items', sa.Column('provider_origin_country', sa.String(length=8), nullable=True))
    op.add_column('media_items', sa.Column('provider_genres', sa.JSON(), nullable=True))
    op.add_column('media_items', sa.Column('provider_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_media_items_anilist_id'), 'media_items', ['anilist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_items_anilist_id'), table_name='media_items')
    op.drop_column('media_items', 'provider_checked_at')
    op.drop_column('media_items', 'provider_genres')
    op.drop_column('media_items', 'provider_origin_country')
    op.drop_column('media_items', 'provider_is_anime')
    op.drop_column('media_items', 'provider_source')
    op.drop_column('media_items', 'anilist_id')
    # ### end Alembic commands ###
