"""initial schema

Revision ID: d0f4d45356ad
Revises:
Create Date: 2026-07-12 21:08:24.349412

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd0f4d45356ad'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_path', sa.String(length=4096), nullable=True),
    sa.Column('old_payload', sa.JSON(), nullable=True),
    sa.Column('new_payload', sa.JSON(), nullable=True),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_created_at'), 'change_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_change_events_type'), 'change_events', ['type'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.String(length=16), nullable=False),
    sa.Column('imdb_id', sa.String(length=32), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('anidb_id', sa.Integer(), nullable=True),
    sa.Column('classification_label', sa.String(length=16), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reasons', sa.JSON(), nullable=True),
    sa.Column('classification_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_items_anidb_id'), 'media_items', ['anidb_id'], unique=False)
    op.create_index(op.f('ix_media_items_imdb_id'), 'media_items', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_tmdb_id'), 'media_items', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_tvdb_id'), 'media_items', ['tvdb_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'number', name='uq_season_item_number')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('container', sa.String(length=32), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('bit_rate', sa.BigInteger(), nullable=True),
    sa.Column('video_width', sa.Integer(), nullable=True),
    sa.Column('video_height', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=True),
    sa.Column('video_dynamic_range', sa.String(length=16), nullable=True),
    sa.Column('audio_summary', sa.String(length=255), nullable=True),
    sa.Column('subtitle_summary', sa.String(length=255), nullable=True),
    sa.Column('episode_numbers', sa.JSON(), nullable=True),
    sa.Column('episode_title', sa.String(length=1024), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('fingerprint_strategy', sa.String(length=16), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_path', 'media_files', ['path'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('codec', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('channels', sa.Float(), nullable=True),
    sa.Column('bit_rate', sa.BigInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_forced', sa.Boolean(), nullable=False),
    sa.Column('is_sdh', sa.Boolean(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('sidecar_path', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_track_file_kind', 'tracks', ['file_id', 'kind'], unique=False)
    op.create_index(op.f('ix_tracks_language'), 'tracks', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_language'), table_name='tracks')
    op.drop_index('ix_track_file_kind', table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('ix_file_path', table_name='media_files')
    op.drop_table('media_files')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_media_items_tvdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_tmdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_imdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_anidb_id'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_change_events_type'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_created_at'), table_name='change_events')
    op.drop_table('change_events')
    # ### end Alembic commands ###
